[package]
name = "skiplist-rs"
version = "0.1.0"
authors = ["Seiichi Uchida <seuchida@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.6"

[dependencies.rand]
version = "0.5"
default-features = false

[dependencies.lazy_static]
version = "1.1.0"
features = ["spin_no_std"]
